= Текстовый редактор

Текстовый редактор со встроенной способностью автоматического распознавания кодировки русскоязычного текста.

Программа открывает файлы в кодировке Koi-8R, Koi-8U, Utf-8, Windows-1251, OEM-866, ISO-8859-5 в читаемом виде.

== Принцип действия

По результатам подсчёта статистики заглавных и строчных букв в русскоязычных текстах Грибоедова "Гробовщик" и А.С. Пушкина "Сказка о царе Салтане" было установлено, что заглавные буквы составляют 2,5 % от общего числа букв русского языка.

В разных кодировках, а именно: Koi-8r/u, Windows-1251, OEM-866 либо ISO-8859-5 русские заглавные и сточные буквы располагаются на разных позициях, но выровнены они по позициям, кратным 16. Ниже приведена сравнительная таблица, которая показывает, где именно располагаются русские буквы в разных кодировках.

|===
| i | KOI-8R/U | OEM-866 | ISO-8859-5 | Windows-1251
| 8 |     |  U  |     |  
| 9 |     |  U  |     |  
| A |     |  L  |     |  
| B |     |     |  U  |  
| C |  L  |     |  U  |  U
| D |  L  |     |  L  |  U
| E |  U  |  L  |  L  |  L
| F |  U  |     |     |  L
|===

Где i - первая цифра в шестнадцатеричной записи символа. U - заглавные буквы, L - строчные буквы.

В остальных местах располагаются знаки пунктуации, диакритические знаки и спецсимволы, которые встречаются значительно реже, чем буквы.

Так как заглавных букв по статистике 2,5%, то на одну заглавную букву в среднем приходится 39 строчных. Поменяем букву L на 39, а U - на 1. Затем ко всем кроме третьей строки прибавим следующую, а к третьей - предпоследнюю, чтобы можно было задействовать специальный алгоритм.

|===
|   | KOI-8R/U | OEM-866 | ISO-8859-5 | Windows-1251
| 1 |  0  |  2  |  0  |  0
| 2 |  0  |  1  |  0  |  0
| 3 |  1  | 78  | 39  | 39
| 4 | 39  |  0  |  2  |  1
| 5 | 78  |  0  | 40  |  2
| 6 | 40  | 39  | 78  | 40
| 7 |  2  | 39  | 39  | 78
| 8 |  1  |  0  |  0  | 39
|===

Теперь становится очевидным алгоритм распознавания кодировки.

1. Если сумма пятой и последней строки меньше первой, то это OEM-866.
2. Если пятая строка меньше последней, то это Windows-1251.
3. Если четвёртая строка больше седьмой, то это либо KOI-8R либо KOI-8U.
4. Если шестая строка больше седьмой, то это ISO-8859-5.

Разница между KOI-8R и KOI-8U состоит в наличии букв IiЇї.

== Авторские права

Copyright (c) 2017-2019 Лев Воробьёв
